// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Context.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230515081811_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApplicationCore.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2901),
                            Name = "Action",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2905),
                            Name = "Adventure",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2906),
                            Name = "Comedy",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2906),
                            Name = "Fantasy",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2907),
                            Name = "Horror",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2907),
                            Name = "Mystrey",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2908),
                            Name = "Romance",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Concrete.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1928, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2620),
                            FirstName = "Stanley",
                            LastName = "Kubrick",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1933, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2634),
                            FirstName = "Roman",
                            LastName = "Polanski",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1963, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2635),
                            FirstName = "Quentin Jerome",
                            LastName = "Tarantino",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1897, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2635),
                            FirstName = "Frank",
                            LastName = "Capra",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1962, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2636),
                            FirstName = "David Leo",
                            LastName = "Fincher",
                            Status = 1
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Concrete.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2748),
                            Description = "A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.",
                            DirectorId = 1,
                            Image = "noimage.png",
                            Name = "Full Metal Jacket",
                            Status = 1,
                            Year = 1987
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2750),
                            Description = "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.",
                            DirectorId = 1,
                            Image = "noimage.png",
                            Name = "The Shining",
                            Status = 1,
                            Year = 1980
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2751),
                            Description = "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
                            DirectorId = 2,
                            Image = "noimage.png",
                            Name = "The Pianist",
                            Status = 1,
                            Year = 2002
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2751),
                            Description = "In 1894, French Captain Alfred Dreyfus is wrongfully convicted of treason and sentenced to life imprisonment at Devil's island.",
                            DirectorId = 2,
                            Image = "noimage.png",
                            Name = "An Officer and A Spy",
                            Status = 1,
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2752),
                            Description = "A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age in 1969 Los Angeles.",
                            DirectorId = 3,
                            Image = "noimage.png",
                            Name = "Once Upon A Time In Hollywood",
                            Status = 1,
                            Year = 2019
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2753),
                            Description = "After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.",
                            DirectorId = 3,
                            Image = "noimage.png",
                            Name = "Kill Bill Volume 1",
                            Status = 1,
                            Year = 2003
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2753),
                            Description = "A Broadway matinee idol famous for his black-face portrayals anonymously joins an amateur acting troupe and falls in love with the leading lady.",
                            DirectorId = 4,
                            Image = "noimage.png",
                            Name = "The Matinee Idol",
                            Status = 1,
                            Year = 1928
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2754),
                            Description = "Naive newspaper cub Clem lands a scoop when he's sent out to cover a murder. In his enthusiasm he writes that the main suspect is Jane. When she confronts Clem she convinces him to help her prove her innocence",
                            DirectorId = 4,
                            Image = "noimage.png",
                            Name = "The Power of The Press",
                            Status = 1,
                            Year = 1928
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2755),
                            Description = "Tells the story of Benjamin Button, a man who starts aging backwards with consequences",
                            DirectorId = 5,
                            Image = "noimage.png",
                            Name = "The Curios Case of Benjamin Button",
                            Status = 1,
                            Year = 2008
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 5, 15, 11, 18, 11, 157, DateTimeKind.Local).AddTicks(2779),
                            Description = "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea and by the co-founder who was later squeezed out of the business.",
                            DirectorId = 5,
                            Image = "noimage.png",
                            Name = "The Social Network",
                            Status = 1,
                            Year = 2010
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Concrete.MovieCategory", b =>
                {
                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("MovieId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MovieCategories");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            MovieId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = 4,
                            CategoryId = 7
                        },
                        new
                        {
                            MovieId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 5,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            MovieId = 6,
                            CategoryId = 3
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            MovieId = 7,
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 8,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryId = 4
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryId = 5
                        },
                        new
                        {
                            MovieId = 9,
                            CategoryId = 6
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 1
                        },
                        new
                        {
                            MovieId = 10,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("ApplicationCore.Entities.Concrete.Movie", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Concrete.Director", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Concrete.MovieCategory", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Concrete.Category", "Category")
                        .WithMany("MovieCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Concrete.Movie", "Movie")
                        .WithMany("MovieCategories")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Concrete.Category", b =>
                {
                    b.Navigation("MovieCategories");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Concrete.Movie", b =>
                {
                    b.Navigation("MovieCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
